### ISSUE TITLE
Trojan? 

### ISSUE THREAD

**Issue by Nehc** [kardolus/chatgpt-cli#52] opened 2024-06-07 13:29 UTC
Windows won't let me download [chatgpt-windows-amd64.exe](https://github.com/kardolus/chatgpt-cli/releases/download/v1.6.1/chatgpt-windows-amd64.exe)- it says:Trojan:Win32/Sabsik.FL.A!ml - it scares. (

**Comment by kardolus** [comment] 2024-06-08 02:54
@Nehc that's wild. I use this script to generate the binaries: https://github.com/kardolus/chatgpt-cli/blob/main/scripts/binaries.sh

Can you help me test this? Run the script on a linux or mac box and try running the binary on your windows box. Alternatively I can try and run windows on a virtual box. Can you provide some details on how to reproduce the error in case I spin up a windows box?

**Comment by kardolus** [comment] 2024-06-08 03:02
PS thanks for reporting this. I really appreciate it.

**Comment by kardolus** [comment] 2024-06-09 00:12
Thanks @Nehc, this may take me a minute to reproduce (I need some help from someone who has both a mac/linux box and a windows box).

**Comment by kardolus** [comment] 2024-06-29 22:37
@Nehc do you happen to have an update on this? Do you have access to a linux to box to create the binary on your side? Alternatively I could create you one from a different box to see if that helps.

**Comment by kardolus** [comment] 2024-06-30 21:52
@Nehc I was thinking, I can create you a binary on an EC2 box. If it gives you the same warning as the binary from my Mac, then it is very likely it is a false alarm. Would that work for you? I don't know many folks with a Windows box :)

**Comment by fmeyer** [comment] 2024-07-20 21:24
Hi, not affected but just helping out having a similar situation; 

Both your GH download URL

https://www.virustotal.com/gui/url/4338f73a5040435b547a332a7bbc27fee0b0ce77f46132905162779400deea01/detection

and binary are flagged

https://www.virustotal.com/gui/file/71c094dd6990bfcaf935f57285432175ee33b9590c6d4502d8cced8b745d054d/behavior

Cleaning those are pretty hard, I suggest you releasing a new binary and ship it in a zip file. 

Since these databases are built by vendors on behalf of their customers it might be hard to clean your previous hash. 

If you notice the pattern continues to happen you need to probably trim down some indirect dependencies that might be sloppy on windows. 

Best,

**Comment by kardolus** [comment] 2024-07-21 20:55
@fmeyer thank you so much! I just released a new binary: https://github.com/kardolus/chatgpt-cli/releases/download/v1.6.1/chatgpt-windows-amd64.exe

I bumped the dependencies first. Hope that this resolves the issue. Fingers crossed!

**Comment by kardolus** [comment] 2024-07-22 15:27
Closing this for now, but feel free to re-open if the updated binary does not resolve the issue. Thanks y'all!

**Closed by kardolus** 2024-07-22 15:27 UTC
