### ISSUE TITLE
Regarding autocompletion

### ISSUE THREAD

**Issue by benbenbang** [kardolus/chatgpt-cli#26] opened 2024-02-20 09:27 UTC
Hi there,

Since we are using `cobra`, any plan to use the completion to help with the flags?
I can do a PR if it's ok for you :)

Thanks

**Comment by benbenbang** [comment] 2024-02-20 23:17
Hello @kardolus,

Sure, let me take a look tmw morning

**Comment by kardolus** [comment] 2024-02-21 13:22
Here's a completion script just for flag completion: https://github.com/kardolus/chatgpt-cli/blob/completion-script/scripts/completion.sh -- not sure if it works across different shells though. I can confirm it works on `GNU bash, version 3.2.57(1)-release (arm64-apple-darwin23)`.

**Comment by kardolus** [comment] 2024-02-21 19:22
Merged it into the `main` branch: https://github.com/kardolus/chatgpt-cli?tab=readme-ov-file#command-line-autocompletion 

I am open to suggestions for something better though :).

**Comment by benbenbang** [comment] 2024-02-21 21:37
Long day :D 
Anyways, we can make it simple or make it "complex"
Maybe I am wrong, or say there's no one way to do it. 
But I can see from the current implementation that you are trying to circuit the command by flags. 
Hence, the command is not that "official" structure, e.g. I was looking for the `rootCmd`

I have a proposal, but it might become a project instead of an issue 😅 

the idea is mainly to 
- convert some flags to commands and extend the utilities
- group the subcommands
- set `prompt`, for example, as a subcommand
- regarding the prompt part, two choices:
    * exec the root command directly, if fail, pass directly to default command, which is `prompt`
    * pre-parse the args and flags in the root, if there's no "arg" in the implementation (could be a list of string), then we fall over the command to `prompt`
    * either way, we can keep it as "it is", i.e., we don't need to use command to invoke `prompt`

and the grouping can be something like
``` bash
$ chatgpt
chatgpt-cli is a cli to...

some other desc 

Enjoy! :)

Chat
  prompt  Run prompt command

Settings Commands
  completion    Generate completion script
  confg  Run config settings command

Other Commands:
  update        Update your chatgpt-cli version
  version       Check your chatgpt-cli version

Use "chatgpt <command> --help" for more information about a given command.
```

like so


And for the `config` subcommand, I am thinking we can extend it to
- generate default config template
- verify config
also, we can keep the flag to take different config paths in the runtime

And so on.

I'd like to stop here first to hear your feedback. Otherwise, I still have some idea can be implemented 😆

**Comment by kardolus** [comment] 2024-02-22 12:51
Thanks @benbenbang! I think the way you are describing the use of cobra/viper makes total sense. However, I really like the current UX (having the simplicity of `chatgpt <message>` without a command). Maybe the current flag completion script is the way to go for now? It's not perfect but it works. I have been enjoying flag completion since yesterday :). Great idea! Thank you.

**Comment by benbenbang** [comment] 2024-02-22 21:52
Alright, nvm, then.

I will create a PR and keep it as it is, and just add a flag to generate a completion script

**Comment by benbenbang** [comment] 2024-02-22 22:24
If you don't mind, I can create another PR to add a `makefile` to run the test / build the binaries?

**Comment by benbenbang** [comment] 2024-02-22 22:27
> Thanks @benbenbang! I think the way you are describing the use of cobra/viper makes total sense. However, I really like the current UX (having the simplicity of `chatgpt <message>` without a command). Maybe the current flag completion script is the way to go for now? It's not perfect but it works. I have been enjoying flag completion since yesterday :). Great idea! Thank you.

My suggestion won't change how you prompt since the default command is the only `prompt` command. It will be triggered when encountering execute error or use `chatgpt prompt xxx`

**Comment by kardolus** [comment] 2024-02-22 22:39
Thank you! This is great. I like Makefiles, so that sounds good to me. Looking at your PR.

**Closed** 2024-02-23 22:28 UTC
